const sharedPlaceholder = 'visual-soon.png';

export const mainBiomeShopPanorama = {
  imageKey: 'panorama_0.png',
  pano: {
    fullWidth: 6985,
    fullHeight: 3493,
    croppedWidth: 6985,
    croppedHeight: 2580,
    croppedX: 0,
    croppedY: 457,
  },
};

export const biomeTypeOptions = [
  ['all', 'All biomes'],
  ['hybrid', 'Hybrid'],
  ['mushroom', 'Mushroom'],
  ['jungle', 'Jungle'],
  ['mountain', 'Mountain'],
  ['badlands', 'Badlands'],
  ['desert', 'Desert'],
  ['cherry', 'Cherry'],
  ['pale', 'Pale'],
  ['plains', 'Plains'],
  ['mangrove', 'Mangrove'],
];

export const biomeInfos = [
  {
    id: '1',
    types: ['mushroom'],
    name: 'Medium Mushroom Island',
    priceLabel: '$7m',
    priceValue: 7,
    status: 'Sold',
    description: 'A well-sized island, perfect for starting your base.',
    imageKey: 'panorama_1.png',
    featured: false,
     pano: {
      fullWidth: 6985,
      fullHeight: 3493,
      croppedWidth: 6985,
      croppedHeight: 2580,
      croppedX: 0,
      croppedY: 457,
    },
  },
  {
    id: '2',
    types: ['mushroom'],
    name: 'Medium Mushroom Island',
    priceLabel: '$8m',
    priceValue: 8,
    status: 'Available',
    description: 'A mushroom shaped like a coiled serpent, waiting for you.',
    imageKey: 'panorama_2.png',
    featured: false,
    pano: {
      fullWidth: 6985,
      fullHeight: 3493,
      croppedWidth: 6985,
      croppedHeight: 2580,
      croppedX: 0,
      croppedY: 457,
    },
  },
  {
    id: '3',
    types: ['mushroom'],
    name: 'Large Mushroom Island',
    priceLabel: '$19m',
    priceValue: 19,
    status: 'Available',
    description: 'Do not underestimate its massive scale.',
    imageKey: 'panorama_3.png',
    featured: false,
    pano: {
      fullWidth: 6985,
      fullHeight: 3493,
      croppedWidth: 6985,
      croppedHeight: 2580,
      croppedX: 0,
      croppedY: 457,
    },
  },
  {
    id: '4',
    types: ['mushroom'],
    name: 'Super Large Mushroom Island',
    priceLabel: '$23m',
    priceValue: 23,
    status: 'Available',
    description: 'Oh godfather, what a size-could this be the largest?',
    imageKey: 'panorama_4.png',
    featured: false,
    pano: {
      fullWidth: 6985,
      fullHeight: 3493,
      croppedWidth: 6985,
      croppedHeight: 2580,
      croppedX: 0,
      croppedY: 457,
    },
  },
  {
    id: '5',
    types: ['mushroom'],
    name: 'Smallest Mushroom Island',
    priceLabel: '$12m',
    priceValue: 12,
    status: 'Available',
    description: 'A rare natural generation, seen only once in a lifetime.',
    imageKey: 'panorama_5.png',
    featured: false,
    pano: {
      fullWidth: 6985,
      fullHeight: 3493,
      croppedWidth: 6985,
      croppedHeight: 2580,
      croppedX: 0,
      croppedY: 457,
    },
  },
  {
    id: '6',
    types: ['mushroom'],
    name: 'Mushroom Behind Spawn',
    priceLabel: '$25m',
    priceValue: 25,
    status: 'Available',
    description: 'The Mother of All Mushrooms rises before you.',
    imageKey: 'panorama_6.png',
    featured: true,
    pano: {
      fullWidth: 6985,
      fullHeight: 3493,
      croppedWidth: 6985,
      croppedHeight: 2580,
      croppedX: 0,
      croppedY: 457,
    },
  },
  {
    id: '7',
    types: ['hybrid','jungle','plains'],
    name: 'Biome Blend Isle',
    priceLabel: '$4m',
    priceValue: 4,
    status: 'Available',
    description: 'Born in a sacred and unusual way-claim me.',
    imageKey: 'panorama_7.png',
    featured: false,
    pano: {
      fullWidth: 6985,
      fullHeight: 3493,
      croppedWidth: 6985,
      croppedHeight: 2580,
      croppedX: 0,
      croppedY: 457,
    },
  },
  {
    id: '8',
    types: ['badlands'],
    name: 'Crimson Heart Badlands',
    priceLabel: '$3m',
    priceValue: 3,
    status: 'Sold',
    description: 'I stand at the center of temptation itself.',
    imageKey: 'panorama_8.png',
    featured: false,
    pano: {
      fullWidth: 6985,
      fullHeight: 3493,
      croppedWidth: 6985,
      croppedHeight: 2580,
      croppedX: 0,
      croppedY: 457,
    },
  },
  {
    id: '9',
    types: ['mountain'],
    name: 'Icewraith Hollow',
    priceLabel: '$4m',
    priceValue: 4,
    status: 'Available',
    description: 'The peak of defense-build your fortress upon me.',
    imageKey: 'panorama_9.png',
    featured: false,
    pano: {
      fullWidth: 6985,
      fullHeight: 3493,
      croppedWidth: 6985,
      croppedHeight: 2580,
      croppedX: 0,
      croppedY: 457,
    },
  },
  {
    id: '10',
    types: ['mountain'],
    name: 'Frostbound Crown',
    priceLabel: '$4m',
    priceValue: 4,
    status: 'Sold',
    description: 'Once a king, now a cursed crown-shaped mountain.',
    imageKey: 'panorama_10.png',
    featured: false,
    pano: {
      fullWidth: 6985,
      fullHeight: 3493,
      croppedWidth: 6985,
      croppedHeight: 2580,
      croppedX: 0,
      croppedY: 457,
    },
  },
  {
    id: '11',
    types: ['mushroom'],
    name: 'Small Mushroom Island',
    priceLabel: '$2.5m',
    priceValue: 2.5,
    status: 'Sold',
    description: 'Small, adorable, and waiting to be claimed by one.',
    imageKey: sharedPlaceholder,
    featured: false,
  },
  {
    id: '12',
    types: ['mushroom'],
    name: 'Medium Mushroom Island',
    priceLabel: '$9.5m',
    priceValue: 9.5,
    status: 'Sold',
    description: 'Hmmmmmmmmmmmmmmmmmm…',
    imageKey: 'panorama_12.png',
    featured: false,
     pano: {
      fullWidth: 6985,
      fullHeight: 3493,
      croppedWidth: 6985,
      croppedHeight: 2580,
      croppedX: 0,
      croppedY: 457,
    },
  },
  {
    id: '13',
    types: ['cherry'],
    name: 'Large Natural Cherry Grove',
    priceLabel: '$7.9m',
    priceValue: 7.9,
    status: 'Sold',
    description: 'I was the greatest of them all - 伝説級の存在.',
    imageKey: 'panorama_13.png',
    featured: false,
    pano: {
      fullWidth: 6985,
      fullHeight: 3493,
      croppedWidth: 6985,
      croppedHeight: 2580,
      croppedX: 0,
      croppedY: 457,
    },
  },
  {
    id: '14',
    types: ['hybrid','mangrove','jungle'],
    name: 'Large Natural Mangrove Grove',
    priceLabel: '$9.5m',
    priceValue: 9.5,
    status: 'Available',
    description: 'The witches’ bane-forge your cavern within me.',
    imageKey: 'panorama_14.png',
    featured: false,
    pano: {
      fullWidth: 6985,
      fullHeight: 3493,
      croppedWidth: 6985,
      croppedHeight: 2580,
      croppedX: 0,
      croppedY: 457,
    },
  },
  {
    id: '15',
    types: ['pale'],
    name: 'Large Mother Pale Biome',
    priceLabel: '$3.4m',
    priceValue: 3.4,
    status: 'Sold',
    description: 'The holy land of death, only the worthy may claim me.',
    imageKey: 'panorama_15.png',
    featured: false,
    pano: {
      fullWidth: 6985,
      fullHeight: 3493,
      croppedWidth: 6985,
      croppedHeight: 2580,
      croppedX: 0,
      croppedY: 457,
    },
  },
  {
    id: '16',
    types: ['pale'],
    name: 'Circular Hollow Pale Biome',
    priceLabel: '$4.8m',
    priceValue: 4.8,
    status: 'Sold',
    description: 'I am the child of death itself.',
    imageKey: 'panorama_16.png',
    featured: false,
    pano: {
      fullWidth: 6985,
      fullHeight: 3493,
      croppedWidth: 6985,
      croppedHeight: 2580,
      croppedX: 0,
      croppedY: 457,
    },
  },
  {
    id: '17',
    types: ['hybrid','mangrove','jungle'],
    name: 'Largest Mangrove Near Border',
    priceLabel: '$8.6m',
    priceValue: 8.6,
    status: 'Available',
    description: 'Come to the far west, my child.',
    imageKey: 'panorama_17.png',
    featured: false,
    pano: {
      fullWidth: 6985,
      fullHeight: 3493,
      croppedWidth: 6985,
      croppedHeight: 2580,
      croppedX: 0,
      croppedY: 457,
    },
  },
  {
    id: '18',
    types: ['hybrid','jungle','desert','plains'],
    name: 'Cool Donut Island',
    priceLabel: '$2m',
    priceValue: 2,
    status: 'Sold',
    description: 'I was once a donut in a past life.',
    imageKey: 'panorama_18.png',
    featured: false,
     pano: {
      fullWidth: 6985,
      fullHeight: 3493,
      croppedWidth: 6985,
      croppedHeight: 2580,
      croppedX: 0,
      croppedY: 457,
    },
  },
  {
    id: '19',
    types: ['jungle'],
    name: 'Isolated Lonely Jungle',
    priceLabel: '$4m',
    priceValue: 4,
    status: 'Sold',
    description: 'I am alone… I need friends… *sniff*.',
    imageKey: 'panorama_19.png',
    featured: false,
     pano: {
      fullWidth: 6985,
      fullHeight: 3493,
      croppedWidth: 6985,
      croppedHeight: 2580,
      croppedX: 0,
      croppedY: 457,
    },
  },
  {
    id: '20',
    types: ['hybrid','jungle','plains'],
    name: 'Mirror Mounds Islands',
    priceLabel: '$4m',
    priceValue: 4,
    status: 'Available',
    description: 'Do I look like something beyond legend?',
    imageKey: 'panorama_20.png',
    featured: false,
    pano: {
      fullWidth: 6985,
      fullHeight: 3493,
      croppedWidth: 6985,
      croppedHeight: 2580,
      croppedX: 0,
      croppedY: 457,
    },
  },
  {
    id: '21',
    types: ['hybrid', 'desert','badlands'],
    name: 'Secluded Geode Desert',
    priceLabel: '$5m',
    priceValue: 5,
    status: 'Sold',
    description: 'Only the one who conquered the sun may claim me.',
    imageKey: 'panorama_21.png',
    featured: false,
    pano: {
      fullWidth: 6985,
      fullHeight: 3493,
      croppedWidth: 6985,
      croppedHeight: 2580,
      croppedX: 0,
      croppedY: 457,
    },
  },
];
