const sharedPlaceholder = 'visual-soon.png';

export const biomeTypeOptions = [
  ['all', 'All biomes'],
  ['hybrid', 'Hybrid'],
  ['mushroom', 'Mushroom'],
  ['jungle', 'Jungle'],
  ['mountain', 'Mountain'],
  ['badlands', 'Badlands'],
  ['desert', 'Desert'],
  ['cherry', 'Cherry'],
  ['pale', 'Pale'],
  ['plains', 'Plains'],
];

export const biomeInfos = [
  {
    id: '1',
    type: 'mushroom',
    name: 'Medium Mushroom Island',
    priceLabel: '$7m',
    priceValue: 7,
    status: 'Sold',
    description: 'A calm natural layout with strong build space and a clean approach line from every side.',
    imageKey: sharedPlaceholder,
    featured: false,
  },
  {
    id: '2',
    type: 'mushroom',
    name: 'Medium Mushroom Island',
    priceLabel: '$8m',
    priceValue: 8,
    status: 'Available',
    description: 'This biome opens with balanced terrain that feels rare, usable, and visually satisfying in one glance.',
    imageKey: sharedPlaceholder,
    featured: false,
  },
  {
    id: '3',
    type: 'mushroom',
    name: 'Large Mushroom Island',
    priceLabel: '$19m',
    priceValue: 19,
    status: 'Available',
    description: 'A strong choice for players who want natural structure, clean borders, and room for ambitious projects.',
    imageKey: sharedPlaceholder,
    featured: false,
  },
  {
    id: '4',
    type: 'mushroom',
    name: 'Super Large Mushroom Island',
    priceLabel: '$23m',
    priceValue: 23,
    status: 'Available',
    description: 'Its terrain shape feels premium from the first flyover, with a layout that supports both beauty and scale.',
    imageKey: sharedPlaceholder,
    featured: false,
  },
  {
    id: '5',
    type: 'mushroom',
    name: 'Smallest Mushroom Island',
    priceLabel: '$12m',
    priceValue: 12,
    status: 'Available',
    description: 'This listing offers a naturally impressive footprint suited for both showcase builds and long-term claims.',
    imageKey: sharedPlaceholder,
    featured: false,
  },
  {
    id: '6',
    type: 'mushroom',
    name: 'Mushroom Behind Spawn',
    priceLabel: '$25m',
    priceValue: 25,
    status: 'Available',
    description: 'A rare generation pattern gives this biome a polished look without needing heavy terraforming first.',
    imageKey: 'panorama.jpg',
    featured: false,
  },
  {
    id: '7',
    type: 'hybrid',
    name: 'Biome Blend Isle',
    priceLabel: '$4m',
    priceValue: 4,
    status: 'Available',
    description: 'Its natural placement makes it ideal for players who want something memorable without forced decoration.',
    imageKey: sharedPlaceholder,
    featured: true,
    pano: {
      fullWidth: 6985,
      fullHeight: 3493,
      croppedWidth: 6985,
      croppedHeight: 2580,
      croppedX: 0,
      croppedY: 457,
    },
  },
  {
    id: '8',
    type: 'badlands',
    name: 'Crimson Heart Badlands',
    priceLabel: '$3m',
    priceValue: 3,
    status: 'Sold',
    description: 'A calm natural layout with strong build space and a clean approach line from every side.',
    imageKey: sharedPlaceholder,
    featured: false,
  },
  {
    id: '9',
    type: 'mountain',
    name: 'Icewraith Hollow',
    priceLabel: '$4m',
    priceValue: 4,
    status: 'Available',
    description: 'This biome opens with balanced terrain that feels rare, usable, and visually satisfying in one glance.',
    imageKey: sharedPlaceholder,
    featured: false,
  },
  {
    id: '10',
    type: 'mountain',
    name: 'Frostbound Crown',
    priceLabel: '$4m',
    priceValue: 4,
    status: 'Sold',
    description: 'A strong choice for players who want natural structure, clean borders, and room for ambitious projects.',
    imageKey: sharedPlaceholder,
    featured: false,
  },
  {
    id: '11',
    type: 'mushroom',
    name: 'Small Mushroom Island',
    priceLabel: '$2.5m',
    priceValue: 2.5,
    status: 'Sold',
    description: 'Its terrain shape feels premium from the first flyover, with a layout that supports both beauty and scale.',
    imageKey: sharedPlaceholder,
    featured: false,
  },
  {
    id: '12',
    type: 'mushroom',
    name: 'Medium Mushroom Island',
    priceLabel: '$7.9m',
    priceValue: 7.9,
    status: 'Sold',
    description: 'This listing offers a naturally impressive footprint suited for both showcase builds and long-term claims.',
    imageKey: sharedPlaceholder,
    featured: false,
  },
  {
    id: '13',
    type: 'cherry',
    name: 'Large Natural Cherry Grove',
    priceLabel: '$9.5m',
    priceValue: 9.5,
    status: 'Sold',
    description: 'A rare generation pattern gives this biome a polished look without needing heavy terraforming first.',
    imageKey: sharedPlaceholder,
    featured: false,
  },
  {
    id: '14',
    type: 'plains',
    name: 'Large Natural Mangrove Grove',
    priceLabel: '$3.4m',
    priceValue: 3.4,
    status: 'Available',
    description: 'Its natural placement makes it ideal for players who want something memorable without forced decoration.',
    imageKey: sharedPlaceholder,
    featured: false,
  },
  {
    id: '15',
    type: 'pale',
    name: 'Large Mother Pale Biome',
    priceLabel: '$4.8m',
    priceValue: 4.8,
    status: 'Sold',
    description: 'A calm natural layout with strong build space and a clean approach line from every side.',
    imageKey: sharedPlaceholder,
    featured: false,
  },
  {
    id: '16',
    type: 'pale',
    name: 'Circular Hollow Pale Biome',
    priceLabel: '$8.6m',
    priceValue: 8.6,
    status: 'Sold',
    description: 'This biome opens with balanced terrain that feels rare, usable, and visually satisfying in one glance.',
    imageKey: sharedPlaceholder,
    featured: false,
  },
  {
    id: '17',
    type: 'plains',
    name: 'Largest Mangrove Near Border',
    priceLabel: '$2m',
    priceValue: 2,
    status: 'Available',
    description: 'A strong choice for players who want natural structure, clean borders, and room for ambitious projects.',
    imageKey: sharedPlaceholder,
    featured: false,
  },
  {
    id: '18',
    type: 'hybrid',
    name: 'Cool Donut Island',
    priceLabel: '$4m',
    priceValue: 4,
    status: 'Sold',
    description: 'Its terrain shape feels premium from the first flyover, with a layout that supports both beauty and scale.',
    imageKey: sharedPlaceholder,
    featured: false,
  },
  {
    id: '19',
    type: 'jungle',
    name: 'Isolated Lonely Jungle',
    priceLabel: '$4m',
    priceValue: 4,
    status: 'Sold',
    description: 'This listing offers a naturally impressive footprint suited for both showcase builds and long-term claims.',
    imageKey: sharedPlaceholder,
    featured: false,
  },
  {
    id: '20',
    type: 'hybrid',
    name: 'Mirror Mounds Islands',
    priceLabel: '$5m',
    priceValue: 5,
    status: 'Available',
    description: 'A rare generation pattern gives this biome a polished look without needing heavy terraforming first.',
    imageKey: sharedPlaceholder,
    featured: false,
  },
  {
    id: '21',
    type: 'hybrid',
    name: 'Secluded Geode Desert',
    priceLabel: '$?m',
    priceValue: null,
    status: 'Available',
    description: 'Its natural placement makes it ideal for players who want something memorable without forced decoration.',
    imageKey: sharedPlaceholder,
    featured: false,
  },
];
